### ISSUE TITLE
Improve general documentation

### ISSUE THREAD

**Issue by LuanGB** [trailblazer/trailblazer-developer#10]
@apotonick I have noticed some documentation is missing or broken within the official page for 2.1 version (and other versions as well). Once I'll be giving a look here to identify were I can help, I would like to improve the documentation as I go. Where I can add those info?

**Comment by apotonick** [comment]
Hi Luan, currently we have new docs in the making. We only need the sidebar menu structure to make it fully working, then we launch the new (WIP) docs and open-source the repo. This time, I spent lots of time to make the build process very smooth, so you will be able to add/fix docs very quickly.

**Comment by apotonick** [comment]
BTW, our website is now "open source" :smirk: https://github.com/trailblazer/website
